name: Simple Build and Security Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    name: Basic Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for secrets
        run: |
          echo "🔍 Checking for potential secrets..."

          # Check for common secret patterns
          if grep -r "sk-[a-zA-Z0-9]\{32,\}" --exclude-dir=.git .; then
            echo "❌ Potential OpenAI API keys found"
            exit 1
          fi

          if grep -r "pk_[a-zA-Z0-9]\{24,\}" --exclude-dir=.git .; then
            echo "❌ Potential Stripe keys found"
            exit 1
          fi

          echo "✅ No obvious secrets detected"

      - name: Privacy compliance check
        run: |
          echo "🔒 Checking privacy compliance..."

          # Check for telemetry
          if grep -r "analytics\|telemetry\|tracking" --exclude-dir=.git --exclude="*.yml" .; then
            echo "❌ Potential privacy violation found"
            exit 1
          fi

          echo "✅ Privacy compliance check passed"

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Basic syntax check
        run: |
          echo "🐍 Checking Python syntax..."
          python -m py_compile scripts/model-manager.py
          python -m py_compile api/secure-proxy.py
          python -m py_compile api/auth-middleware.py
          echo "✅ Python syntax check passed"

      - name: Build Docker image
        run: |
          echo "🐳 Building Docker image..."
          docker build -f docker/Dockerfile.privacy-focused -t private-llm-test .
          echo "✅ Docker build successful"

  deploy:
    name: Deploy to Registry
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          echo "🚀 Building and pushing Docker image..."

          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/private-llm-cloud"

          docker build -f docker/Dockerfile.privacy-focused -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

          echo "✅ Image pushed to $IMAGE_NAME:latest"